/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FinalFantanosyVI;

import static FinalFantanosyVI.FinalFantanosy.backgroundName;
import javax.swing.ButtonGroup;
import static FinalFantanosyVI.FinalFantanosy.lifeName;
import static FinalFantanosyVI.FinalFantanosy.songName;
import static FinalFantanosyVI.FrmStartMenu.mp;
import java.awt.Graphics;
import java.io.File;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.ImageIcon;
/*
 * ICS3U CULMINATING ASSIGNMENT: FINAL FANTANOSY VI
 * AUTHORS: HARIS AYUB, JESSE WANG, TIM HE
 * DATE: JANUARY 23RD 2017
 */
public class FrmOptions extends javax.swing.JFrame {
    public FrmOptions() {
        initComponents();
        //this allows only one button to be selected per category
        
        ButtonGroup musicGroup = new ButtonGroup();
        musicGroup.add(rbtnITAOTS);
        musicGroup.add(rbtnTongHua);
        musicGroup.add(rbtnCanIKickIt);
        musicGroup.add(rbtnMute);
        ButtonGroup backgroundGroup = new ButtonGroup();
        backgroundGroup.add(rbtnUU);
        backgroundGroup.add(rbtnMPP);
        backgroundGroup.add(rbtnTLOP);
        ButtonGroup lifeGroup = new ButtonGroup();
        lifeGroup.add(rbtnRide);
        lifeGroup.add(rbtnKanye);
        lifeGroup.add(rbtnKdot);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnITAOTS = new javax.swing.JRadioButton();
        rbtnTongHua = new javax.swing.JRadioButton();
        rbtnCanIKickIt = new javax.swing.JRadioButton();
        lblITAOTS = new javax.swing.JLabel();
        lblTongHua = new javax.swing.JLabel();
        lblCanIKickIt = new javax.swing.JLabel();
        lblMute = new javax.swing.JLabel();
        rbtnMute = new javax.swing.JRadioButton();
        rbtnUU = new javax.swing.JRadioButton();
        rbtnMPP = new javax.swing.JRadioButton();
        rbtnTLOP = new javax.swing.JRadioButton();
        btnOk = new javax.swing.JButton();
        rbtnRide = new javax.swing.JRadioButton();
        rbtnKanye = new javax.swing.JRadioButton();
        rbtnKdot = new javax.swing.JRadioButton();
        lblLife = new javax.swing.JLabel();
        lblBGM = new javax.swing.JLabel();
        lblBGImage = new javax.swing.JLabel();
        lblConfirm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OPTIONS");
        setBackground(new java.awt.Color(204, 0, 204));

        rbtnITAOTS.setText("Soft and sweet");
        rbtnITAOTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnITAOTSActionPerformed(evt);
            }
        });

        rbtnTongHua.setText("编程");
        rbtnTongHua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTongHuaActionPerformed(evt);
            }
        });

        rbtnCanIKickIt.setText("Yes you can!");
        rbtnCanIKickIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCanIKickItActionPerformed(evt);
            }
        });

        lblITAOTS.setText("In The Aeroplane Over The Sea");

        lblTongHua.setText("Tong Hua");

        lblCanIKickIt.setText("Can I Kick It?");

        lblMute.setText("No Music");

        rbtnMute.setText(":(");
        rbtnMute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMuteActionPerformed(evt);
            }
        });

        rbtnUU.setText("Untitled Unmastered");
        rbtnUU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnUUActionPerformed(evt);
            }
        });

        rbtnMPP.setText("Merriweather Post Pavillion");
        rbtnMPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMPPActionPerformed(evt);
            }
        });

        rbtnTLOP.setText("The Life Of Pablo");
        rbtnTLOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTLOPActionPerformed(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        rbtnRide.setText("MC Ride");
        rbtnRide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRideActionPerformed(evt);
            }
        });

        rbtnKanye.setText("Kanye West");
        rbtnKanye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnKanyeActionPerformed(evt);
            }
        });

        rbtnKdot.setText("Kendrick Lamar");
        rbtnKdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnKdotActionPerformed(evt);
            }
        });

        lblLife.setText("LIFE SKIN");

        lblBGM.setText("BACKGROUND MUSIC");

        lblBGImage.setText("BACKGROUND IMAGE");

        lblConfirm.setText("CONFIRM SETTINGS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnKanye)
                    .addComponent(rbtnRide)
                    .addComponent(rbtnKdot))
                .addGap(146, 146, 146)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTongHua)
                                            .addComponent(lblCanIKickIt)
                                            .addComponent(lblMute))
                                        .addGap(107, 107, 107))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblITAOTS)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnITAOTS)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnMute)
                                            .addComponent(rbtnCanIKickIt)
                                            .addComponent(rbtnTongHua))
                                        .addGap(12, 12, 12))))
                            .addComponent(lblBGM, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lblLife, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblConfirm)
                            .addGap(138, 138, 138))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnUU)
                                    .addComponent(rbtnTLOP))
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblBGImage)
                                .addGap(132, 132, 132))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rbtnMPP)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBGM, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBGImage))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblITAOTS)
                            .addComponent(rbtnITAOTS))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnTongHua)
                            .addComponent(lblTongHua))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbtnCanIKickIt)
                            .addComponent(lblCanIKickIt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(rbtnUU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtnMPP)
                        .addGap(15, 15, 15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMute)
                            .addComponent(rbtnMute)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(rbtnTLOP)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLife, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirm))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnKdot)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnKanye)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnRide))
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnCanIKickItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCanIKickItActionPerformed
        // TODO add your handling code here:
        //if this song selected, set it as the song and play as a sample
        
        mp.stop();
        songName = "Can I Kick It.mp3";
        Media myMedia = new Media(new File(songName).toURI().toString());
        mp = new MediaPlayer(myMedia);
        mp.play();
    }//GEN-LAST:event_rbtnCanIKickItActionPerformed

    private void rbtnMuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMuteActionPerformed
        // TODO add your handling code here:
        //if this (lack of a) song selected, set it as the song and play as a sample
        
        mp.stop();
        songName = "4'33.mp3";
        Media myMedia = new Media(new File(songName).toURI().toString());
        mp = new MediaPlayer(myMedia);
        mp.play();
    }//GEN-LAST:event_rbtnMuteActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        // when the player is done with options, end sampling the music and go back to main menu
        
        mp.stop();
        this.setVisible(false);
        new FrmStartMenu().setVisible(true);
    }//GEN-LAST:event_btnOkActionPerformed

    private void rbtnUUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnUUActionPerformed
        // TODO add your handling code here:
        //if this background is chosen, set it as background for game
        
        backgroundName = "UU.jpg";
    }//GEN-LAST:event_rbtnUUActionPerformed

    private void rbtnKdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnKdotActionPerformed
        // TODO add your handling code here:
        //if this life skin is chosen, set it as background for game
        
        lifeName = "kdotLife.png";
    }//GEN-LAST:event_rbtnKdotActionPerformed

    private void rbtnKanyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnKanyeActionPerformed
        // TODO add your handling code here:
        //if this life skin is chosen, set it as background for game
        
        lifeName = "kanyeLife.png";
    }//GEN-LAST:event_rbtnKanyeActionPerformed

    private void rbtnRideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRideActionPerformed
        // TODO add your handling code here:
        //if this life skin is chosen, set it as background for game
        
        lifeName = "rideLife.png";
    }//GEN-LAST:event_rbtnRideActionPerformed

    private void rbtnITAOTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnITAOTSActionPerformed
        // TODO add your handling code here:
        //if this song selected, set it as the song and play as a sample
        
        mp.stop();
        songName = "03 In The Aeroplane Over The Sea.mp3";
        Media myMedia = new Media(new File(songName).toURI().toString());
        mp = new MediaPlayer(myMedia);
        mp.play();
    }//GEN-LAST:event_rbtnITAOTSActionPerformed

    private void rbtnTongHuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTongHuaActionPerformed
        // TODO add your handling code here:
        //if this song selected, set it as the song and play as a sample
        
        mp.stop();
        songName = "Tong Hua.mp3";
        Media myMedia = new Media(new File(songName).toURI().toString());
        mp = new MediaPlayer(myMedia);
        mp.play();
    }//GEN-LAST:event_rbtnTongHuaActionPerformed

    private void rbtnMPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMPPActionPerformed
        // TODO add your handling code here:
        //if this background is chosen, set it as background for game
        
        backgroundName = "animalcollective.jpg";
    }//GEN-LAST:event_rbtnMPPActionPerformed

    private void rbtnTLOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTLOPActionPerformed
        // TODO add your handling code here:
        //if this background is chosen, set it as background for game
        
        backgroundName = "tlop.jpg";
    }//GEN-LAST:event_rbtnTLOPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmOptions().setVisible(true);
        });
    }
    @Override
    public void paint(Graphics g) {
        //display life skins and background
        
        super.paint(g);
        ImageIcon rideLife = new ImageIcon("rideLife.png");
        ImageIcon kanyeLife = new ImageIcon("kanyeLife.png");
        ImageIcon kdotLife = new ImageIcon("kdotLife.png");
        ImageIcon uu = new ImageIcon("UU.jpg");
        ImageIcon mpp = new ImageIcon("animalcollective.jpg");
        ImageIcon tlop = new ImageIcon("tlop.jpg");
        g.drawImage(kdotLife.getImage(), 100, 400, 30, 30, lblLife);
        g.drawImage(kanyeLife.getImage(), 100, 450, 30, 30, lblLife);
        g.drawImage(rideLife.getImage(), 100, 500, 30, 30, lblLife);
        g.drawImage(uu.getImage(), 500, 100, 40, 40, lblLife);
        g.drawImage(mpp.getImage(), 500, 150, 40, 40, lblLife);
        g.drawImage(tlop.getImage(), 500, 200, 40, 40, lblLife);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblBGImage;
    private javax.swing.JLabel lblBGM;
    private javax.swing.JLabel lblCanIKickIt;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblITAOTS;
    private javax.swing.JLabel lblLife;
    private javax.swing.JLabel lblMute;
    private javax.swing.JLabel lblTongHua;
    private javax.swing.JRadioButton rbtnCanIKickIt;
    private javax.swing.JRadioButton rbtnITAOTS;
    private javax.swing.JRadioButton rbtnKanye;
    private javax.swing.JRadioButton rbtnKdot;
    private javax.swing.JRadioButton rbtnMPP;
    private javax.swing.JRadioButton rbtnMute;
    private javax.swing.JRadioButton rbtnRide;
    private javax.swing.JRadioButton rbtnTLOP;
    private javax.swing.JRadioButton rbtnTongHua;
    private javax.swing.JRadioButton rbtnUU;
    // End of variables declaration//GEN-END:variables
}
